---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi
workspace:
  path: /drone/src

steps:
- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    dockerfile: /drone/src/Dockerfile
    repo: ch1ch1/openvpn
    tag: [ "latest"]
    username: ch1ch1
    password:
      from_secret: dockerhub-password

---
kind: signature
hmac: 00a86328fe50f3cf016d4aba0cfba2ff8364528f1967afd4fab220e76cbf359b

...
