kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi

workspace:
  path: /drone/src

steps:

- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    dockerfile: /drone/src/Dockerfile
    repo: ch1ch1/openvpn
    tag: [ "latest"]
    username: ch1ch1
    password:
      from_secret: dockerhub-password
