---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
  drone: nimi
workspace:
  path: /drone/src

steps:
- name: build
  image: plugins/docker
  pull: if-not-exists
  settings:
    dockerfile: /drone/src/Dockerfile
    repo: ch1ch1/openvpn
    tag: [ "latest","2.4.9"]
    username: ch1ch1
    password:
      from_secret: dockerhub-password

---
kind: signature
hmac: 2defe5a9b18c3e3b510005e314f9f6d07e329faf51a9d92ef64b739894829c5a

...
